### ISSUE TITLE
Splitting SBEP Ship Models into Small, Medium, Large

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/sbep#100]
A recent change in the size limits of an addon on the workshop has nulled out the current structure of the addon from being able to be updated ( as sbep is over 300mb uncompressed )

We have decided to split it up into 3 separate workshop addons ( ship part sizes )

- Small
- Medium
- Large

As an example this would put Smallbridge(Small), Medbridge(Medium) and Slyfo's items(Large) into their own respective addons. 

However there will be copies of certain life support models, player models, etc allowing them to still be accessed no matter which part of the addon is installed. 

This is really only to split up the size of ships people can create on certain servers. It will also give server owners the choice of allowing the creation of certain size ships to be built.

~~We're going to use CAF to handle loading the correct parts into the spawn menus and what not.~~ CAF wouldn't work for people using SBEP without Spacebuild, unless sbep gets CAF too ;)

Any thoughts?

**Comment by Facial-Reconstruction** [comment]
I mean, it's not like we have a choice right? Go ahead, people need their SBEP fix 👍

**Comment by generalwrex** [comment]
@Facial-Reconstruction Haha, yeah  Just needed to let as many people know what's going to happen so that there isn't too much confusion when the sbep people are subscribed to disappears from the workshop!

**Comment by TheMerkyShadow** [comment]
I mean we could compress the files into a smaller size? Then in the workshop client lua check if the models exist and tell the clients to decompress them instructions available on a github readme?

**Comment by TheMerkyShadow** [comment]
packs = {
		"", --Small
		"", --Medium
		""  --Large
	{

	for k, v in pairs ( packs ) do
        if SERVER then
			resource.AddWorkshop( v )
		else
			steamworks.Subscribe( v )
			if k == table.Count( packs ) then
				steamworks.ApplyAddons()
			end
		end
	end
	
	
/autorun/ folder
In sbep we can remove the models. And make it legacy files only.
And add this script to ensure the server and player downloads the correct addons.

**Comment by generalwrex** [comment]
We've decided to change how we're going to do this for the upcoming SB4 👍 A new issue will be created when we can ;)
