### ISSUE TITLE
Smallbridge parts are all Errors.

### ISSUE THREAD

**Issue by H3xx69** [spacebuild/sbep#68]
The only smallbridge parts that are showing up and are spawnable are the wings, one or two engine parts, and a cockpit thing that doesn't look like it goes to anything. The rest are nothing but errors. I made sure that it wasn't a problem with Tortoise by downloading the zip from Github and installing that. Still kaput. I don't know how to collect a log message, otherwise I would do that for you.

**Comment by nirahiel** [comment]
Well i'm going to work on my SB3 server so I can check that for you if you want. Please note that i'm on the workshop version for now so me not having the error doesn't mean there is no error. it just means there is no error on the WORKSHOP version. But i'll get back to you if I find something. Cheers.

**Comment by generalwrex** [comment]
Is this still an issue?
