### ISSUE TITLE
Getting Spacebuild back on its feet!

### ISSUE THREAD

**Issue by generalwrex** [spacebuild/sbep#78]
this is a shadow copy of the issue on the main spacebuild repository located

at https://github.com/SnakeSVx/spacebuild/issues/81

If you would like to contribute to getting spacebuild back please leave a comment here to let people know that we'll have active developers!!

The contributors named below are not set in stone, they are just ones I can pull off the top of my head, or have said something in another issue or on steam!

I will update this list as more arrive ;)
# Contributors
-   SnakeSVx
-   generalwrex
-   TheMerkyShadow
-   X-Coder
-   thrimbor

**Comment by generalwrex** [comment]
I created a facepunch thread for us!

https://facepunch.com/showthread.php?t=1519499&p=50363396

**Comment by generalwrex** [comment]
I made SBEP public on the workshop for now as I need to take off for a few days for family matters, I'm leaving sunday night so I will barely have any time to watch things until the 11th. 

http://steamcommunity.com/sharedfiles/filedetails/?id=695227522

**Comment by nirahiel** [comment]
Well i'm okay to be coder, i believe i already have the rights added ? (I received an email telling me so)
I was a contributor on the old SBEP github project. May I be contributor on the SB3 as well ? There are some things I want to improve.

**Comment by generalwrex** [comment]
Lets use the forums now https://spacebuildmod.com/forum
