### ISSUE TITLE
Elev system needs a sanity check.

### ISSUE THREAD

**Issue by Shigbeard** [spacebuild/sbep#95]
So the elevator system needs a sanity check. ENT:GetFloorNum()... to be precise. When it returns 0, self.FloorTable[self:GetFloorNum()] returns nil. This variable is used in math.Round, which requires a number and will error on a nil value. By assuming floor 0 is floor 1, you can avoid this issue.

https://github.com/Shigbeard/sbep/tree/elev_system-sanitypatch I made a patch, but if I make a pull request it will break git blame, as it thinks I've rewritten the whole file because I'm shit at git.

**Comment by Shigbeard** [comment]
Ooops, let me edit OP.

**Comment by nirahiel** [comment]
We already have a branch where we are working on the elevator system. I
think x-coder can see your changes and do something about it. I can't.
Japan expo for 4 days.

**Comment by Shigbeard** [comment]
Well the change i've made has allowed me to use the elevators now as opposed to having them simply spam errors so I'll use my changes until an official patch is made to master.

**Comment by X-Coder** [comment]
Thank you, I will look into it. By the way, the trouble you had with git is because you somehow changed all the line endings, but I can do the commit for you too.

**Comment by X-Coder** [comment]
@Shigbeard can you describe what steps you did to show up this error?

**Comment by Shigbeard** [comment]
Spawn a lift with any number of floors. Wire the elevator in such a way that floornum will be 0 until a floor is selected for the first time.
I have some E2 that will serve this purpose

**Comment by X-Coder** [comment]
This should fix your issue by preventing adding invalid range to CallFloorTable in first place.

**Comment by Shigbeard** [comment]
It certainly looks like it will. Thank you.
