### ISSUE TITLE
No SVN Trunk

### ISSUE THREAD

**Issue by chexo3** [spacebuild/sbep#98]
When you try to do an svn checkout at https://github.com/spacebuild/sbep/trunk it says there is no such url. This is a problem for automated checking out as it forces you to use a more complicated method.

**Comment by X-Coder** [comment]
You should now use a git compatible client, not one for svn repositories, svn was the old method back in the days. Use for example https://tortoisegit.org (which is the counterpart for tortoisesvn, if you used it before), or https://gitextensions.github.io which I use when I develop, but the last one is bit more than you will need.

**Comment by generalwrex** [comment]
I know this was answered awhile ago, but if you HAVE to use SVN the trunk is actually located at https://github.com/spacebuild/sbep.git 
But using git is the best way ;)
